//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localisation.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localisation.Localisation.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Management.
        /// </summary>
        internal static string AboutWindow_ApplicationName {
            get {
                return ResourceManager.GetString("AboutWindow_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor:.
        /// </summary>
        internal static string AboutWindow_Author {
            get {
                return ResourceManager.GetString("AboutWindow_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walker.st@outlook.com.
        /// </summary>
        internal static string AboutWindow_AuthorEmail {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Stock Management.
        /// </summary>
        internal static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AppText_Comment {
            get {
                return ResourceManager.GetString("AppText_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last stocktaking.
        /// </summary>
        internal static string AppText_LastStocktaking {
            get {
                return ResourceManager.GetString("AppText_LastStocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocktaking overview.
        /// </summary>
        internal static string AppText_StocktakingOverview {
            get {
                return ResourceManager.GetString("AppText_StocktakingOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string FileImport_BrowseFile {
            get {
                return ResourceManager.GetString("FileImport_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has column names.
        /// </summary>
        internal static string FileImport_ColumnNames {
            get {
                return ResourceManager.GetString("FileImport_ColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter:.
        /// </summary>
        internal static string FileImport_DelimiterCsvTxt {
            get {
                return ResourceManager.GetString("FileImport_DelimiterCsvTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t chosen a file yet, please choose a file before importing data.
        /// </summary>
        internal static string FileImport_FileChoose {
            get {
                return ResourceManager.GetString("FileImport_FileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format:.
        /// </summary>
        internal static string FileImport_FileFormat {
            get {
                return ResourceManager.GetString("FileImport_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path:.
        /// </summary>
        internal static string FileImport_FilePath {
            get {
                return ResourceManager.GetString("FileImport_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import.
        /// </summary>
        internal static string FileImport_Heading {
            get {
                return ResourceManager.GetString("FileImport_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string FileImport_ImportData {
            get {
                return ResourceManager.GetString("FileImport_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during import.
        /// </summary>
        internal static string FileImport_ImportError {
            get {
                return ResourceManager.GetString("FileImport_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet:.
        /// </summary>
        internal static string FileImport_Sheet {
            get {
                return ResourceManager.GetString("FileImport_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        internal static string FileImportTitle {
            get {
                return ResourceManager.GetString("FileImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainMenu_Button_SettingsButton {
            get {
                return ResourceManager.GetString("MainMenu_Button_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Management.
        /// </summary>
        internal static string MainMenu_Button_StockManagementButton {
            get {
                return ResourceManager.GetString("MainMenu_Button_StockManagementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string OldCustomersMenu_Button_Close {
            get {
                return ResourceManager.GetString("OldCustomersMenu_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload data.
        /// </summary>
        internal static string OldCustomersMenu_Button_ReloadData {
            get {
                return ResourceManager.GetString("OldCustomersMenu_Button_ReloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Customers.
        /// </summary>
        internal static string OldCustomersMenuTitle {
            get {
                return ResourceManager.GetString("OldCustomersMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SearchWindow_Button_Close {
            get {
                return ResourceManager.GetString("SearchWindow_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all.
        /// </summary>
        internal static string SearchWindow_Button_SearchAll {
            get {
                return ResourceManager.GetString("SearchWindow_Button_SearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search next.
        /// </summary>
        internal static string SearchWindow_Button_SearchNext {
            get {
                return ResourceManager.GetString("SearchWindow_Button_SearchNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current grid:.
        /// </summary>
        internal static string SearchWindow_CurrentGrid {
            get {
                return ResourceManager.GetString("SearchWindow_CurrentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string SearchWindow_UpperLowerCase {
            get {
                return ResourceManager.GetString("SearchWindow_UpperLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to seach:.
        /// </summary>
        internal static string SearchWindowMenu_SearchText {
            get {
                return ResourceManager.GetString("SearchWindowMenu_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchwindow.
        /// </summary>
        internal static string SearchWindowTitle {
            get {
                return ResourceManager.GetString("SearchWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string SettingsMenu_BrowseFile {
            get {
                return ResourceManager.GetString("SettingsMenu_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the customer data file.
        /// </summary>
        internal static string SettingsMenu_BrowseFileTitle {
            get {
                return ResourceManager.GetString("SettingsMenu_BrowseFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data preview:.
        /// </summary>
        internal static string SettingsMenu_DataPreview {
            get {
                return ResourceManager.GetString("SettingsMenu_DataPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter:.
        /// </summary>
        internal static string SettingsMenu_Delimiter {
            get {
                return ResourceManager.GetString("SettingsMenu_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the customer file.
        /// </summary>
        internal static string SettingsMenu_FileDilalogCustomerFile {
            get {
                return ResourceManager.GetString("SettingsMenu_FileDilalogCustomerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional settings.
        /// </summary>
        internal static string SettingsMenu_GroupBox_AdditionalSettings {
            get {
                return ResourceManager.GetString("SettingsMenu_GroupBox_AdditionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsMenu_Language {
            get {
                return ResourceManager.GetString("SettingsMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid file.
        /// </summary>
        internal static string SettingsMenu_ValidFile {
            get {
                return ResourceManager.GetString("SettingsMenu_ValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenuTitle {
            get {
                return ResourceManager.GetString("SettingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StockManagementMenu_Button_About {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        internal static string StockManagementMenu_Button_AdvancedSearch {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string StockManagementMenu_Button_BasicSearch {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_BasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string StockManagementMenu_Button_Cancel {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string StockManagementMenu_Button_Count {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count selection: .
        /// </summary>
        internal static string StockManagementMenu_Button_CountSelection {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_CountSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete filters.
        /// </summary>
        internal static string StockManagementMenu_Button_DeleteFilters {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_DeleteFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export table.
        /// </summary>
        internal static string StockManagementMenu_Button_ExportData {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string StockManagementMenu_Button_ImportData {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StockManagementMenu_Button_Ok {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records found: .
        /// </summary>
        internal static string StockManagementMenu_Button_RecordsFound {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_RecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application directory.
        /// </summary>
        internal static string StockManagementMenu_Button_RootFolder {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string StockManagementMenu_Button_SaveChanges {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string StockManagementMenu_Button_Settings {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        internal static string StockManagementMenu_Button_SortAscending {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        internal static string StockManagementMenu_Button_SortDescending {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string StockManagementMenu_Button_Sum {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum selection: .
        /// </summary>
        internal static string StockManagementMenu_Button_SumSelection {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_SumSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage unused values.
        /// </summary>
        internal static string StockManagementMenu_Button_UnusedValues {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_UnusedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string StockManagementMenu_Button_Update {
            get {
                return ResourceManager.GetString("StockManagementMenu_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string StockManagementMenu_CheckBox_SelectAll {
            get {
                return ResourceManager.GetString("StockManagementMenu_CheckBox_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new sheet has been added, please click here to fill it with data..
        /// </summary>
        internal static string StockManagementMenu_NewSheetAdded {
            get {
                return ResourceManager.GetString("StockManagementMenu_NewSheetAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string StockManagementMenu_TabPage_SheetTitle {
            get {
                return ResourceManager.GetString("StockManagementMenu_TabPage_SheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update.
        /// </summary>
        internal static string Updater_ApplicationUpdate {
            get {
                return ResourceManager.GetString("Updater_ApplicationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update process was successful.
        /// </summary>
        internal static string Updater_ApplicationUpdateMessage {
            get {
                return ResourceManager.GetString("Updater_ApplicationUpdateMessage", resourceCulture);
            }
        }
    }
}
